"""
Django settings for binarysystem project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

from pathlib import Path
import os


# -------------------------------------------------
# BASE DIRECTORY
# -------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent



# -------------------------------------------------
# SECURITY
# -------------------------------------------------

SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-development-key-change-this"
)


DEBUG = False


ALLOWED_HOSTS = [
    "bkgparamount.com",
    "www.bkgparamount.com",
    "148.135.136.60"
]


# -------------------------------------------------
# APPLICATIONS
# -------------------------------------------------

INSTALLED_APPS = [

    # Django Default Apps

    'django.contrib.admin',

    'django.contrib.auth',

    'django.contrib.contenttypes',

    'django.contrib.sessions',

    'django.contrib.messages',

    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    # Project Apps

    'accounts',

    'dashboard',

    'referral',

    'administrator',

]



# -------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True
MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

   

]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# -------------------------------------------------
# URL CONFIGURATION
# -------------------------------------------------

ROOT_URLCONF = 'binarysystem.urls'



# -------------------------------------------------
# TEMPLATE CONFIGURATION
# -------------------------------------------------

TEMPLATES = [

    {

        'BACKEND':
        'django.template.backends.django.DjangoTemplates',


        'DIRS':
        [

            BASE_DIR / 'templates'

        ],


        'APP_DIRS':
        True,


        'OPTIONS':
        {

            'context_processors':
            [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]



WSGI_APPLICATION = 'binarysystem.wsgi.application'

ASGI_APPLICATION = 'binarysystem.asgi.application'



# -------------------------------------------------
# DATABASE
# -------------------------------------------------

# Development Database
# Change to MySQL before production


DATABASES = {


    'default':

    {


        'ENGINE':
        'django.db.backends.sqlite3',


        'NAME':
        BASE_DIR / 'db.sqlite3',


    }

}



# -------------------------------------------------
# MYSQL CONFIGURATION (Production)
# -------------------------------------------------

"""
Use this after installing MySQL


DATABASES = {


'default':

{


'ENGINE':
'django.db.backends.mysql',


'NAME':
'binarysystem',


'USER':
'root',


'PASSWORD':
'your_mysql_password',


'HOST':
'localhost',


'PORT':
'3306',


}


}


"""



# -------------------------------------------------
# PASSWORD VALIDATION
# -------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [

    {

        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',

    },


    {

        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',

    },

]



# -------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------

LANGUAGE_CODE = 'en-us'


TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True


USE_TZ = True



# -------------------------------------------------
# STATIC FILES
# -------------------------------------------------

STATIC_URL = '/static/'


STATICFILES_DIRS = [

    BASE_DIR / 'static'

]


STATIC_ROOT = BASE_DIR / 'staticfiles'

# -------------------------------------------------
# MEDIA FILES
# -------------------------------------------------

MEDIA_URL = '/media/'


MEDIA_ROOT = BASE_DIR / 'media'



# -------------------------------------------------
# AUTHENTICATION SETTINGS
# -------------------------------------------------

LOGIN_URL = '/login/'


LOGIN_REDIRECT_URL = '/dashboard/'


LOGOUT_REDIRECT_URL = '/login/'



# -------------------------------------------------
# SESSION SECURITY
# -------------------------------------------------

SESSION_COOKIE_AGE = 3600


SESSION_EXPIRE_AT_BROWSER_CLOSE = True



# -------------------------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Referral bonus per direct referral shown in weekly dashboard cards.
REFERRAL_BONUS_AMOUNT = int(os.environ.get("REFERRAL_BONUS_AMOUNT", "500"))



SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"


