# Generated by Django 6.0.6 on 2026-06-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], max_length=10, null=True)),
                ('level', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_node', to='accounts.investor')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_children', to='accounts.investor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sponsor', 'position'), name='unique_binary_position')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('monday', models.DateField()),
                ('saturday', models.DateField()),
                ('total_referrals', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('CURRENT', 'CURRENT'), ('PREVIOUS', 'PREVIOUS')], default='CURRENT', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_activity', to='accounts.investor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor', 'week_number'), name='unique_week_activity')],
            },
        ),
    ]
