# Generated by Django 6.0.1 on 2026-07-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyactivity',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
