# Generated by Django 6.0.6 on 2026-06-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_investor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='aadhar',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
