# Generated by Django 6.0.1 on 2026-07-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_investor_aadhar_alter_investor_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING')], default='ACTIVE', max_length=20),
        ),
    ]
