# Generated by Django 6.0.1 on 2026-07-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_investor_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
